### ISSUE TITLE
Nodes metadata missing

### ISSUE THREAD

**Issue by davidwickerhf** [maastrichtlawtech/case-explorer-ui#52]
There seems to be another issue. Could you please check why Retrieved Nodes and Edges are undefined? It doesn't matter the scenario (cluster or otherwise), the information seems to be missing. The data is obtained from NetworkStatistics lambda function. The code is placed under docker/networkstats. I think the info is not parsed at all, so we are seeing it as empty.

#### Possible reasons to look into
- datafetcher amplify function
-  DataBar/Header.tsx component --> Selected itemId is not having the information that we need
- https://github.com/maastrichtlawtech/case-explorer-ui/blob/prod/components/CaseLawExplorer/components/DataBar/Header.tsx

What it should look like:
![image](https://github.com/maastrichtlawtech/case-explorer-ui/assets/37675067/fed0b58d-947a-4f08-bdac-dc11ba084f2a)

**Comment by shashankmc** [comment]
@davidwickerhf - https://github.com/maastrichtlawtech/perfect-graph/blob/f3f4fd2555f0329650b8bc7e2b54011f8e0485c3/src/components/GraphEditor/DataBar/index.tsx#L131 The "Node Information" is taken from Perfect graph. From the commit history (git blame), this was there before - {` id: ${item?.id}`} which is now changed to 'node information' without node details. Most likely that.

Needs to be changed to  {`Node information:\n ${item?.id}`}. 

Could you check it out and update the perfect library? Then update the package version here and test?

**Comment by davidwickerhf** [comment]
<img width="496" alt="Screenshot 2024-08-28 at 13 24 01" src="https://github.com/user-attachments/assets/0a76e017-895e-4cbb-9e7a-a695292660da">

Is this related?

**Comment by shashankmc** [comment]
![Image](https://github.com/user-attachments/assets/fb6bd527-0892-4b2d-b2f5-d4b5d7988824)

Error is in Lambda function. The code where it fails - https://github.com/maastrichtlawtech/case-explorer-ui/blob/e218279491d1a3dfcc5fe91bcc6d7537d5678009/amplify/backend/function/datafetcher/src/index.py#L8 

After checking a couple of things, there was an env variable missing in the lambda function. The environment variable was called DDB_TABLE_NAME. Updated the lambda function with the appropriate env variable.

Validated it on the platform. Issue resolved.
